import {
  Button,
  Paper,
  Typography,
} from "@mui/material";
import { useNavigate } from "react-router-dom";
import CustomContainer from "../../components/customContainer/CustomContainer";
import { useEffect } from "react";

const NotFound = () => {
  // console.error(error);
  const navigate = useNavigate();

  useEffect(() => {
    var json = `
    [
        {
            "codigo": "103",
            "descripcion": "UNIPOLAR 1 X 0,50",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.44,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 0,
            "resist_aislacion_70c": 0.011,
            "tension_electrodos": "4 Kv.",
            "resist_electrica_20c": 0,
            "tension_en_agua": 0,
            "cantidad_hilos": 7,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 0.91,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.11,
            "diametro_conductor_Produccion": 2.1,
            "matriz": "2.15",
            "cantidad_almas": 1,
            "diametro_cableado": 2.1,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.44,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.455,
            "kgs_totales": 0.895,
            "kgs_terminado": 0.868,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "",
            "obs2": "",
            "obs3": "",
            "paso_final": "",
            "precio": 0
        },
        {
            "codigo": "104",
            "descripcion": "UNIPOLAR 1 X 0,75",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.44,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 2.8,
            "resist_aislacion_70c": 0.011,
            "tension_electrodos": "4 Kv.",
            "resist_electrica_20c": 26,
            "tension_en_agua": 0,
            "cantidad_hilos": 10,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.09,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.29,
            "diametro_conductor_Produccion": 2.3,
            "matriz": "2.40",
            "cantidad_almas": 1,
            "diametro_cableado": 2.3,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.5,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.65,
            "kgs_totales": 1.15,
            "kgs_terminado": 1.116,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "",
            "precio": 0
        },
        {
            "codigo": "105V",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        },
        {
            "codigo": "105R",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        },
        {
            "codigo": "105M",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        },
        {
            "codigo": "105C",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        },
        {
            "codigo": "105B",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        },
        {
            "codigo": "105N",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        },
        {
            "codigo": "105VB",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        },
        {
            "codigo": "105RB",
            "descripcion": "UNIPOLAR 1 X 1",
            "espesor_aislacion_promedio": 0.6,
            "espesor_aislacion_minimo": 0.53,
            "espesor_envoltura_promedio": 0,
            "espesor_envoltura_minimo": 0,
            "diametro_nominal": 0,
            "diametro_maximo_extremo": 3.2,
            "resist_aislacion_70c": 0.01,
            "tension_electrodos": "5 Kv.",
            "resist_electrica_20c": 19.5,
            "tension_en_agua": 0,
            "cantidad_hilos": 13,
            "diametros_hilos": 0.3,
            "diametro_cuerda": 1.24,
            "pico_cuerda": 0,
            "diametro_conductor_calculado": 2.44,
            "diametro_conductor_Produccion": 2.45,
            "matriz": "2.60",
            "cantidad_almas": 1,
            "diametro_cableado": 2.45,
            "pico_relleno": 0,
            "diametro_relleno_calculado": 0,
            "diametro_relleno_produccion": 0,
            "espesor": 0,
            "diametro_sobre_fleje": 0,
            "diametro_envoltura_calculado": 0,
            "diametro_envoltura_produccion": 0,
            "matriz_envoltura": 0,
            "kgs_a": 0.54,
            "kgs_r": 0,
            "kgs_v": 0,
            "kgs_cu": 0.845,
            "kgs_totales": 1.385,
            "kgs_terminado": 1.344,
            "kgs_produccion": 0,
            "kgs_armadura_metalica": 0,
            "paso": "50",
            "matriz_relleno": "",
            "pico": "",
            "obs1": "Distancia pico a matriz    mm.",
            "obs2": "",
            "obs3": "",
            "paso_final": "50",
            "precio": 0
        }
    ]
    `;
    const regex = /"([^"]+)":/g;
    json = json.replace(regex, "$1:");
    console.log(json);
  },[]);

  return (
    <CustomContainer>
      <Paper
        sx={{
          marginY: 8,
          padding: 3,
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          alignContent: "center",
        }}
      >
        <Typography component="h1" variant="h1" gutterBottom>
          404 :(
        </Typography>
        <Typography component="p" variant="body1" gutterBottom>
          La página que buscas no existe.
        </Typography>
        <br />
        <Button variant="contained" onClick={() => navigate("/")}>
          Ir a página principal
        </Button>
      </Paper>
    </CustomContainer>
  );
};

export default NotFound;
